@startuml
' *************** Entités de la structure de l'organisation ***************

class Organisation {
  - nom : String
  - universites : List<Universite>
}

class Universite {
  - nom : String
  - departements : List<Departement>
  - responsableUniversite : User
}

class User {
  - id : String
  - name : String
  - phone : String
  - email : String
  - password : String
  - role : String "USER, ADMIN, TEACHER, DELEGATE, SUPERVISOR"
  - subjects : List<Subject>
  - programme : Programme
}

class Departement {
  - nom : String
  - programmes : List<Programme>
}

class Programme {
  - nom : String
  - subjects : List<Subject>
}

class AcademicYear {
  - periode : String  "ex: 2024-2025"
}

class Subject {
  - nom : String
  - volumeHoraire : int
}

' *************** Entités liées aux cours et à l'émargement ***************

class ClassSession {
  - date : Date
  - heureDebut : Time
  - heureFin : Time
  - academicYear : AcademicYear
  - subject : Subject
  - professor : User
  - classRepresentative : User
}

' *************** Autres entités ***************

class Emargement {
  - id : String
  - timestamp : DateTime
  - status : String  "En attente, Présent, Signalé absent"
  - classSession : ClassSession
  - professor : User
}

class Notification {
  - id : String
  - timestamp : DateTime
  - message : String
  - status : String  "Envoyée, Confirmée"
  - emargement : Emargement
  - recipient : User
}

' *************** Associations ***************

Organisation "1" -- "1..*" Universite : contient
Universite "1" -- "1..*" Departement : comprend
Departement "1" -- "1..*" Programme : offre
Programme "1" -- "1..*" Subject : propose
Universite "1" -- "1" User : gérée_par

ClassSession "1" -- "1" AcademicYear : planifiée_dans
ClassSession "1" -- "1" Subject : concerne
ClassSession "1" -- "1" User : donné_par
ClassSession "1" -- "1" User : validée_par

Emargement "1" -- "1" ClassSession : appartient_à
Emargement "1" -- "1" User : concerne

Notification "1" -- "1" Emargement : déclenchée_par
Notification "1" -- "1" User : adressée_à

User "0..*" -- "1" Programme : inscrit_dans

@enduml
